from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton

LanguageButton1 = InlineKeyboardButton(text='Українська🇺🇦', callback_data='lang_ukr')
LanguageButton2 = InlineKeyboardButton(text='Русский🇷🇺', callback_data='lang_rus')
LanguageButton3 = InlineKeyboardButton(text='English🇬🇧', callback_data='lang_eng')
Button1 = InlineKeyboardButton(text="BTC", callback_data='cc_bitcoin')
Button2 = InlineKeyboardButton(text="ETH", callback_data='cc_ethereum')
Button3 = InlineKeyboardButton(text="BNB", callback_data='cc_binancecoin')
Button4 = InlineKeyboardButton(text="LTC", callback_data='cc_litecoin')
Button5 = InlineKeyboardButton(text="DOGE", callback_data='cc_dogecoin')
Button6 = InlineKeyboardButton(text="XRP", callback_data='cc_ripple')
Button7 = InlineKeyboardButton(text="ADA", callback_data='cc_cardano')
Button8 = InlineKeyboardButton(text="SOL", callback_data='cc_solana')
Button9 = InlineKeyboardButton(text="DOT", callback_data='cc_polkadot')
Button10 = InlineKeyboardButton(text="TRX", callback_data='cc_tron')
Button11 = InlineKeyboardButton(text="LINK", callback_data='cc_chainlink')
Button12 = InlineKeyboardButton(text="NEAR", callback_data='cc_near')
Button13 = InlineKeyboardButton(text="MATIC", callback_data='cc_matic-network')
Button14 = InlineKeyboardButton(text="ATOM", callback_data='cc_cosmos')
Button15 = InlineKeyboardButton(text="AVAX", callback_data='cc_avalanche-2')
Button16 = InlineKeyboardButton(text="UNI", callback_data='cc_uniswap')
ButtonBack = InlineKeyboardButton(text="⬅️", callback_data='back')
ButtonAll = InlineKeyboardButton(text="ALL➕", callback_data='cc_all')
RemoveAll = InlineKeyboardButton(text="ALL➖", callback_data='cc_remove')
ButtonSend = InlineKeyboardButton(text="📈", callback_data='back_send')
ListMenu = InlineKeyboardMarkup(row_width=4).add(Button1, Button2, Button3, Button4, Button5, Button6, Button7,
                                                 Button8, Button9, Button10, Button11, Button12, Button13, Button14,
                                                 Button15, Button16, ButtonBack, ButtonAll, RemoveAll, ButtonSend)
LanguageMenu = InlineKeyboardMarkup(row_width=1).add(LanguageButton1, LanguageButton2, LanguageButton3, ButtonBack)
